In [5]:
!pip install django

from django.shortcuts import render, HttpResponse
import numpy as np
import pandas as pd
import os
from nlp.settings import BASE_DIR
import json


# Create your views here.
from nlp_proj.models import Hotel

def index(request):
    txtfile = pd.read_csv(os.path.join(BASE_DIR, 'nlp_proj/dummydata/dummy.txt') , sep=",", names=["txt", "category", "label"])
    overall = txtfile.groupby("label").count().iloc[:3, 1].values.tolist()
    overall_keys = ["negative", "positive"]
    overall_dic = {i : j for i, j in zip(overall_keys, overall)}
    overall_json = json.dumps(overall_dic)

    #sents8_json = pd.read_csv(os.path.join(BASE_DIR, 'nlp_proj/dummydata/FastText_8_sentiment_results.txt') , sep=",", names=["txt", "category", "sentiment", "rawIdx"])
    #overall = txtfile.groupby("label").count().iloc[:3, 1].values
    #overall_dic = {"neg" : overall[0], "pos" : overall[1]}
    #overall_json = json.dumps(overall_dic)

    #sents17_json = pd.read_csv(os.path.join(BASE_DIR, 'nlp_proj/dummydata/FastText_17_sentiment_results.txt') , sep=",", names=["txt", "category", "sentiment", "rawIdx"])


    # review_all = Hotel.objects.all()  # .get(), .filter(), ...
    # request가 POST -> Form을 완성.
    # Form이 유효하면 저장.\
    # if request.method == "POST":
    #     form = CoffeeForm(request.POST)  # 완성된 Form
    #     if form.is_valid():  # 채워진 Form이 유효하다면
    #         form.save()  # Form을 Model에 저장

    # form = CoffeeForm()
    return render(request, 'index.html', {"overall_json" : overall_json})

Collecting django
  Downloading Django-3.1.7-py3-none-any.whl (7.8 MB)
Collecting sqlparse>=0.2.2
  Using cached sqlparse-0.4.1-py3-none-any.whl (42 kB)
Collecting asgiref<4,>=3.2.10
  Using cached asgiref-3.3.1-py3-none-any.whl (19 kB)
Requirement already satisfied: pytz in c:\users\hoon2\anaconda3\lib\site-packages (from django) (2020.1)
Installing collected packages: sqlparse, asgiref, django
Successfully installed asgiref-3.3.1 django-3.1.7 sqlparse-0.4.1

ModuleNotFoundError: No module named 'nlp'

In [144]:
txtfile = pd.read_csv('dummydata/dummy.txt', sep=",", names=["txt", "category", "label"])
overall = txtfile.groupby("label").count().iloc[:3, 1].values.tolist()
overall_keys = ["negative", "positive"]
overall_dic = {i : j for i, j in zip(overall_keys, overall)}
overall_dic

{'negative': 517, 'positive': 350}

In [145]:
txtfile = pd.read_csv('dummydata/FastText_8_sentiment_results.txt', sep=",")
txtfile

,text,category,sentiment,rawsentenceIdx
0,실내 수영장도 개방형이라서 좋았다,깨끗,1,3
1,객실 인테리어 및 편의시설은 훌륭했다,깨끗,1,3
2,란 생각이 마구 들더군요,깨끗,0,4
3,신라는 반얀에 비해 층 고도 높고 룸도 쾌적하고 시설도 더 깔끔하고 조식이 훨씬 맛...,깨끗,1,4
4,3 청결 서비스 숙소 내 청결도는 상당히 만족했습니다,깨끗,1,6
...,...,...,...,...
5035,아기랑 편하게 체크인 아웃할 수 있게 배려해 주셔서 감사했습니다,기타,1,1623
5036,조식 맛있지만 사람이 많아서 계속 줄 줄줄 ㅠㅠ 실내 수영장은 평일은 아기 출입금지...,기타,0,1623
5037,아기랑 갈분은 참고하 세용 하튼 한 번은 가 볼 만한 특고급 호텔 잘 다녀왔습니당,기타,1,1623
5038,체크인 시간보다 일찍 갔더니 바로 체크인 되지는 않았고 연락처로 체크인 가능할 때 ...,기타,0,1626
5039,혼자 갔지만 친절한 직원들 덕에 편하게 식사를 마치고 주변 구경을 하니 체크인 가능...,기타,1,1626

In [146]:
category_pos_cnt = txtfile.groupby("category").sum()
category_pos_cnt

          sentiment  rawsentenceIdx
category
기타             1207         2037838
깨끗              699          748467
소리                4           18462
위치              217          353758
조식              643          869081
직원              528          561636
화장실             118          247201

In [147]:
category_total_cnt = txtfile.groupby("category").count()
category_total_cnt

          text  sentiment  rawsentenceIdx
category
기타        2072       2072            2072
깨끗         842        842             842
소리          21         21              21
위치         306        306             306
조식         884        884             884
직원         650        650             650
화장실        265        265             265

In [148]:
category_total_cnt["pos_cnt"] = category_pos_cnt["sentiment"]
category_total_cnt["neg_cnt"] = category_total_cnt["sentiment"] - category_total_cnt["pos_cnt"]

In [149]:
category_total_cnt

          text  sentiment  rawsentenceIdx  pos_cnt  neg_cnt
category
기타        2072       2072            2072     1207      865
깨끗         842        842             842      699      143
소리          21         21              21        4       17
위치         306        306             306      217       89
조식         884        884             884      643      241
직원         650        650             650      528      122
화장실        265        265             265      118      147

In [150]:
import math

category_total_cnt["pos_ratio"] = category_total_cnt["pos_cnt"] / (category_total_cnt["pos_cnt"] + category_total_cnt["neg_cnt"])
category_total_cnt["neg_ratio"] = category_total_cnt["neg_cnt"] / (category_total_cnt["pos_cnt"] + category_total_cnt["neg_cnt"])

category_total_cnt["pos_cnt_sqrt"] = category_total_cnt["pos_cnt"].apply(math.sqrt)
category_total_cnt["neg_cnt_sqrt"] = category_total_cnt["neg_cnt"].apply(math.sqrt)

scaling_val = max(category_total_cnt["pos_cnt_sqrt"] + category_total_cnt["neg_cnt_sqrt"])
category_total_cnt["pos_cnt_sqrt_modified"] = category_total_cnt["pos_cnt_sqrt"] / (scaling_val*8)
category_total_cnt["neg_cnt_sqrt_modified"] = category_total_cnt["neg_cnt_sqrt"] / (scaling_val*8)

category_total_cnt

,category,text,sentiment,rawsentenceIdx,pos_cnt,neg_cnt,pos_ratio,neg_ratio,pos_cnt_sqrt,neg_cnt_sqrt,pos_cnt_sqrt_modified,neg_cnt_sqrt_modified
0,기타,2072,2072,2072,1207,865,0.582529,0.417471,34.741906,29.410882,0.067694,0.057306
1,깨끗,842,842,842,699,143,0.830166,0.169834,26.438608,11.958261,0.051515,0.023300
2,소리,21,21,21,4,17,0.190476,0.809524,2.000000,4.123106,0.003897,0.008034
3,위치,306,306,306,217,89,0.709150,0.290850,14.730920,9.433981,0.028703,0.018382
4,조식,884,884,884,643,241,0.727376,0.272624,25.357445,15.524175,0.049408,0.030248
5,직원,650,650,650,528,122,0.812308,0.187692,22.978251,11.045361,0.044773,0.021522
6,화장실,265,265,265,118,147,0.445283,0.554717,10.862780,12.124356,0.021166,0.023624

In [151]:
def mean_norm(df_input):
    return df_input.apply(lambda x: (x-x.mean())/ x.std(), axis=0)

category_total_cnt["pos_cnt_sqrt_modified_normalized"] = (category_total_cnt["pos_cnt_sqrt_modified"] - category_total_cnt["pos_cnt_sqrt_modified"].mean()) / (category_total_cnt["pos_cnt_sqrt_modified"].std() * 50)
category_total_cnt["neg_cnt_sqrt_modified_normalized"] = (category_total_cnt["neg_cnt_sqrt_modified"] - category_total_cnt["neg_cnt_sqrt_modified"].mean()) / (category_total_cnt["neg_cnt_sqrt_modified"].std() * 50)
category_total_cnt

,text,sentiment,rawsentenceIdx,pos_cnt,neg_cnt,pos_ratio,neg_ratio,pos_cnt_sqrt,neg_cnt_sqrt,pos_cnt_sqrt_modified,neg_cnt_sqrt_modified,pos_cnt_sqrt_modified_normalized,neg_cnt_sqrt_modified_normalized
category,,,,,,,,,,,,,
기타,2072,2072,2072,1207,865,0.582529,0.417471,34.741906,29.410882,0.067694,0.057306,0.027471,0.040739
깨끗,842,842,842,699,143,0.830166,0.169834,26.438608,11.958261,0.051515,0.023300,0.012420,-0.003597
소리,21,21,21,4,17,0.190476,0.809524,2.000000,4.123106,0.003897,0.008034,-0.031880,-0.023501
위치,306,306,306,217,89,0.709150,0.290850,14.730920,9.433981,0.028703,0.018382,-0.008803,-0.010010
조식,884,884,884,643,241,0.727376,0.272624,25.357445,15.524175,0.049408,0.030248,0.010460,0.005461
직원,650,650,650,528,122,0.812308,0.187692,22.978251,11.045361,0.044773,0.021522,0.006147,-0.005916
화장실,265,265,265,118,147,0.445283,0.554717,10.862780,12.124356,0.021166,0.023624,-0.015814,-0.003175

In [152]:
category_total_cnt["pos_ratio_calib"] = category_total_cnt["pos_ratio"] + category_total_cnt["pos_cnt_sqrt_modified_normalized"]
category_total_cnt["neg_ratio_calib"] = category_total_cnt["neg_ratio"] + category_total_cnt["neg_cnt_sqrt_modified_normalized"]
category_total_cnt

,text,sentiment,rawsentenceIdx,pos_cnt,neg_cnt,pos_ratio,neg_ratio,pos_cnt_sqrt,neg_cnt_sqrt,pos_cnt_sqrt_modified,neg_cnt_sqrt_modified,pos_cnt_sqrt_modified_normalized,neg_cnt_sqrt_modified_normalized,pos_ratio_calib,neg_ratio_calib
category,,,,,,,,,,,,,,,
기타,2072,2072,2072,1207,865,0.582529,0.417471,34.741906,29.410882,0.067694,0.057306,0.027471,0.040739,0.610000,0.458210
깨끗,842,842,842,699,143,0.830166,0.169834,26.438608,11.958261,0.051515,0.023300,0.012420,-0.003597,0.842586,0.166236
소리,21,21,21,4,17,0.190476,0.809524,2.000000,4.123106,0.003897,0.008034,-0.031880,-0.023501,0.158596,0.786022
위치,306,306,306,217,89,0.709150,0.290850,14.730920,9.433981,0.028703,0.018382,-0.008803,-0.010010,0.700348,0.280840
조식,884,884,884,643,241,0.727376,0.272624,25.357445,15.524175,0.049408,0.030248,0.010460,0.005461,0.737835,0.278086
직원,650,650,650,528,122,0.812308,0.187692,22.978251,11.045361,0.044773,0.021522,0.006147,-0.005916,0.818455,0.181776
화장실,265,265,265,118,147,0.445283,0.554717,10.862780,12.124356,0.021166,0.023624,-0.015814,-0.003175,0.429469,0.551542

In [156]:
category_total_cnt["pos_score"] = (category_total_cnt["pos_ratio_calib"] + category_total_cnt["pos_cnt_sqrt_modified"])
category_total_cnt["neg_score"] = (category_total_cnt["neg_ratio_calib"] + category_total_cnt["neg_cnt_sqrt_modified"])

category_total_cnt["pos_score_scaled"] = category_total_cnt["pos_score"] * 100 
category_total_cnt["neg_score_scaled"] = category_total_cnt["neg_score"] * 100

category_total_cnt

,text,sentiment,rawsentenceIdx,pos_cnt,neg_cnt,pos_ratio,neg_ratio,pos_cnt_sqrt,neg_cnt_sqrt,pos_cnt_sqrt_modified,neg_cnt_sqrt_modified,pos_cnt_sqrt_modified_normalized,neg_cnt_sqrt_modified_normalized,pos_ratio_calib,neg_ratio_calib,pos_score,neg_score,pos_score_scaled,neg_score_scaled
category,,,,,,,,,,,,,,,,,,,
기타,2072,2072,2072,1207,865,0.582529,0.417471,34.741906,29.410882,0.067694,0.057306,0.027471,0.040739,0.610000,0.458210,0.677693,0.515516,67.769346,51.551600
깨끗,842,842,842,699,143,0.830166,0.169834,26.438608,11.958261,0.051515,0.023300,0.012420,-0.003597,0.842586,0.166236,0.894101,0.189537,89.410076,18.953683
소리,21,21,21,4,17,0.190476,0.809524,2.000000,4.123106,0.003897,0.008034,-0.031880,-0.023501,0.158596,0.786022,0.162493,0.794056,16.249322,79.405622
위치,306,306,306,217,89,0.709150,0.290850,14.730920,9.433981,0.028703,0.018382,-0.008803,-0.010010,0.700348,0.280840,0.729050,0.299222,72.905036,29.922171
조식,884,884,884,643,241,0.727376,0.272624,25.357445,15.524175,0.049408,0.030248,0.010460,0.005461,0.737835,0.278086,0.787244,0.308334,78.724363,30.833432
직원,650,650,650,528,122,0.812308,0.187692,22.978251,11.045361,0.044773,0.021522,0.006147,-0.005916,0.818455,0.181776,0.863227,0.203298,86.322723,20.329756
화장실,265,265,265,118,147,0.445283,0.554717,10.862780,12.124356,0.021166,0.023624,-0.015814,-0.003175,0.429469,0.551542,0.450634,0.575166,45.063437,57.516565

In [158]:
category_total_cnt = category_total_cnt.reset_index()

In [159]:
category_dic = {}
for i in category_total_cnt:
    category_dic[i] = [str(category_total_cnt[i][size]) for size in range(len(category_total_cnt["category"]))]
category_dic

{'category': ['기타', '깨끗', '소리', '위치', '조식', '직원', '화장실'],
 'text': ['2072', '842', '21', '306', '884', '650', '265'],
 'sentiment': ['2072', '842', '21', '306', '884', '650', '265'],
 'rawsentenceIdx': ['2072', '842', '21', '306', '884', '650', '265'],
 'pos_cnt': ['1207', '699', '4', '217', '643', '528', '118'],
 'neg_cnt': ['865', '143', '17', '89', '241', '122', '147'],
 'pos_ratio': ['0.5825289575289575',
  '0.830166270783848',
  '0.19047619047619047',
  '0.7091503267973857',
  '0.7273755656108597',
  '0.8123076923076923',
  '0.44528301886792454'],
 'neg_ratio': ['0.4174710424710425',
  '0.16983372921615203',
  '0.8095238095238095',
  '0.2908496732026144',
  '0.27262443438914025',
  '0.18769230769230769',
  '0.5547169811320755'],
 'pos_cnt_sqrt': ['34.741905532080416',
  '26.43860813280457',
  '2.0',
  '14.730919862656235',
  '25.357444666211933',
  '22.978250586152114',
  '10.862780491200215'],
 'neg_cnt_sqrt': ['29.410882339705484',
  '11.958260743101398',
  '4.123105625617661',
  '9.433981132056603',
  '15.524174696260024',
  '11.045361017187261',
  '12.12435565298214'],
 'pos_cnt_sqrt_modified': ['0.0676936784133113',
  '0.05151492438965413',
  '0.0038969467780518518',
  '0.02870280534825912',
  '0.049408306145811355',
  '0.04477250979348678',
  '0.021165838717933597'],
 'neg_cnt_sqrt_modified': ['0.0573063215866887',
  '0.023300352836966468',
  '0.008033761591659104',
  '0.01838186118838497',
  '0.030248441282252295',
  '0.02152159201417371',
  '0.023623984348921757'],
 'pos_cnt_sqrt_modified_normalized': ['0.027470822240710638',
  '0.012419566297185962',
  '-0.031879912358417174',
  '-0.008802775163975306',
  '0.01045975837149449',
  '0.006147030871041216',
  '-0.015814490258039837'],
 'neg_cnt_sqrt_modified_normalized': ['0.040738640145657326',
  '-0.0035972532560304333',
  '-0.023501346182793932',
  '-0.010009825208722768',
  '0.005461442025462087',
  '-0.00591634467221255',
  '-0.003175312851359741'],
 'pos_ratio_calib': ['0.6099997797696681',
  '0.842585837081034',
  '0.1585962781177733',
  '0.7003475516334103',
  '0.7378353239823542',
  '0.8184547231787335',
  '0.4294685286098847'],
 'neg_ratio_calib': ['0.4582096826166998',
  '0.1662364759601216',
  '0.7860224633410156',
  '0.2808398479938916',
  '0.2780858764146023',
  '0.18177596302009513',
  '0.5515416682807157'],
 'pos_score': ['0.6776934581829794',
  '0.8941007614706881',
  '0.16249322489582516',
  '0.7290503569816694',
  '0.7872436301281656',
  '0.8632272329722203',
  '0.4506343673278183'],
 'neg_score': ['0.5155160042033885',
  '0.18953682879708805',
  '0.7940562249326747',
  '0.2992217091822766',
  '0.3083343176968546',
  '0.20329755503426883',
  '0.5751656526296375'],
 'pos_score_scaled': ['67.76934581829795',
  '89.4100761470688',
  '16.249322489582514',
  '72.90503569816694',
  '78.72436301281655',
  '86.32272329722203',
  '45.06343673278183'],
 'neg_score_scaled': ['51.55160042033885',
  '18.953682879708804',
  '79.40562249326747',
  '29.922170918227657',
  '30.83343176968546',
  '20.32975550342688',
  '57.516565262963745']}

In [65]:
import json

total_cnt = {"positive" : int(category_total_cnt["pos_cnt"].sum()) , "negative" : int(category_total_cnt["neg_cnt"].sum())}

int

In [104]:
txtfile = pd.read_csv('dummydata/dummy.txt', sep=",", names=["txt", "category", "label"])
print(txtfile.groupby("label").count().iloc[:3, 1])
overall = txtfile.groupby("label").count().iloc[:3, 1].values.tolist()
print(overall)
overall_keys = ["negative", "positive"]
overall_dic = {i : j for i, j in zip(overall_keys, overall)}
print(overall_dic)
#overall_json = json.dumps(overall_dic)

label
0    517
1    350
Name: category, dtype: int64
[517, 350]
{'negative': 517, 'positive': 350}